apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ansibleforms
  name: ansibleforms-env
  labels:
    app.kubernetes.io/name: ansibleforms-env
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: ansibleforms
data:
  LOG_CONSOLE_LEVEL: debug
  LOG_LEVEL: debug
  MYSQL_DATABASE: "AnsibleForms"
